{% set version = "1.10.0" %}


package:
  name: gtest
  version: {{ version }}

source:
  url: https://github.com/google/googletest/archive/release-{{ version }}.tar.gz
  sha256: 9dc9157a9a1551ec7a7e43daea9a694a0bb5fb8bec81235d8a1e6ef64c716dcb

build:
  number: 1

requirements:
  build:
    - {{ compiler('cxx') }}
    - python {{ python }}
    - cmake {{ cmake }}
    - ninja {{ ninja }}
  host: []  # Empty host dependency section

outputs:
  - name: gtest
    version: {{ version }}
    requirements:
      build:
        - {{ compiler('cxx') }}
        - python {{ python }}
        - cmake {{ cmake }}
        - ninja {{ ninja }}
      run_constrained:
        - gmock {{ version }}
    files:
      -  lib/libgtest*                                          # [linix]
      -  include/gtest                                          # [linix]
      -  lib/pkgconfig/gtest*.pc                                # [linix]
      -  lib/cmake/GTest                                        # [linix]
    test:
      commands:
        - test ! -f ${PREFIX}/lib/libgtest.a                    # [linix]
        - test ! -f ${PREFIX}/lib/libgtest_main.a               # [linix]
        - test -f ${PREFIX}/lib/libgtest${SHLIB_EXT}            # [linix]
        - test -f ${PREFIX}/lib/pkgconfig/gtest.pc              # [linix]
        - test -f ${PREFIX}/lib/pkgconfig/gtest_main.pc         # [linix]
        - test -d ${PREFIX}/include/gtest                       # [linix]

  - name: gmock
    version: {{ version }}
    requirements:
      build:
        - {{ compiler('cxx') }}
        - python {{ python }}
        - cmake {{ cmake }}
        - ninja {{ ninja }}
      host:
        - {{ pin_subpackage('gtest', exact=True) }}
      run:
        - {{ pin_subpackage('gtest', exact=True) }}
    files:
      -  include/gmock                                          # [linix]
      -  lib/libgmock*                                          # [linix]
      -  lib/pkgconfig/gmock*.pc                                # [linix]
      -  lib/cmake/GTest                                        # [linix]
    test:
      commands:
        - test ! -f ${PREFIX}/lib/libgmock.a                    # [linix]
        - test ! -f ${PREFIX}/lib/libgmock_main.a               # [linix]
        - test -f ${PREFIX}/lib/libgmock${SHLIB_EXT}            # [linix]
        - test -f ${PREFIX}/lib/pkgconfig/gmock.pc              # [linix]
        - test -f ${PREFIX}/lib/pkgconfig/gmock_main.pc         # [linix]
        - test -d ${PREFIX}/include/gmock                       # [linix]

about:
  home: https://github.com/google/googletest
  license: BSD-3-Clause
  license_family: BSD
  license_file: googletest/LICENSE
  summary: Google's C++ test framework

extra:
  recipe-maintainers:
    - open-ce/open-ce-dev-team
